kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: eks-cube-test-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0801376f7651dfb79
  directoryPerms: "700"
